name: Manual Release

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: pull LFS
        run: git lfs pull

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: "Release v1.0.0"
          draft: false
          prerelease: false

      - name: Upload arm64 script
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./arm-crosschain-arm64.sh
          asset_name: arm-crosschain-arm64.sh
          asset_content_type: text/x-shellscript

      - name: Upload amd64 script
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./arm-crosschain-amd64.sh
          asset_name: arm-crosschain-amd64.sh
          asset_content_type: text/x-shellscript
