name: Manual Release

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: pull LFS
        run: git lfs pull

      - name: Upload arm64 script
        uses: actions/upload-artifact@v4
        with:
          path: ./arm-crosschain-arm64.sh
          name: arm-crosschain-arm64.sh

      - name: Upload amd64 script
        uses: actions/upload-artifact@v4
        with:
          path: ./arm-crosschain-amd64.sh
          name: arm-crosschain-amd64.sh
